// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// Port defines model for Port.
type Port struct {
	Action   *string `json:"action,omitempty"`
	Port     *string `json:"port,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
}

// ChangePortResponseOK defines model for ChangePortResponseOK.
type ChangePortResponseOK struct {
	Data *string `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetPortsResponseOK defines model for GetPortsResponseOK.
type GetPortsResponseOK struct {
	Data *[]Port `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetStateResponseOK defines model for GetStateResponseOK.
type GetStateResponseOK struct {
	Data *string `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetVersionResponseOK defines model for GetVersionResponseOK.
type GetVersionResponseOK struct {
	Data *bool `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseServiceUnavailable defines model for ResponseServiceUnavailable.
type ResponseServiceUnavailable = BaseResponse

// OpenOrClosePortJSONRequestBody defines body for OpenOrClosePort for application/json ContentType.
type OpenOrClosePortJSONRequestBody = Port

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get State
	// (GET /firewall)
	GetState(ctx echo.Context) error
	// Get Opened Ports
	// (GET /port)
	GetOpenedPorts(ctx echo.Context) error
	// Open or Close a Port
	// (POST /port)
	OpenOrClosePort(ctx echo.Context) error
	// Get Version
	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetState converts echo context to params.
func (w *ServerInterfaceWrapper) GetState(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetState(ctx)
	return err
}

// GetOpenedPorts converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenedPorts(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetOpenedPorts(ctx)
	return err
}

// OpenOrClosePort converts echo context to params.
func (w *ServerInterfaceWrapper) OpenOrClosePort(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.OpenOrClosePort(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/firewall", wrapper.GetState)
	router.GET(baseURL+"/port", wrapper.GetOpenedPorts)
	router.POST(baseURL+"/port", wrapper.OpenOrClosePort)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX3W7cNhN9FWK+7yIBZGtht0AgIBexixqGi24Qp+2F11jMUrMSE4pkSWrt7ULvXpCS",
	"9r/rn8SBr2yRwzNnDg/J2QVwXRmtSHkH2QIsOaOVo/hxXqIq6KO2/lM3PLwK41wrT8qHf9EYKTh6oVX6",
	"xWkVxhwvqcI4K+VwCtnNAv5vaQoZ/C9dpUvbOJeeoaM+ATTJAozVhqwXLYscfQSje6yMJMjA1ZyTc5CA",
	"n5s44K1QBTTNckRPvhD30NwmYAnzoZJzyLytqQlBOTluhQmsIYPhFTQJXJAPlbrXUKrwVMWBQ1iBLawq",
	"RmtxvleCQyVfe/T0unbX1kqF3fzeu/snWSe0elXFBs7LqiZaS0L1bYX22c8w/0R/1+T8I8pc8llARc5h",
	"EXKfYc56iCb5RikeU8BWwn7xNdmZ4PSHwhkKiZOW53Mq6pDYOtQPqWxv4mXmaI0N0GzbOMsaFlvI3QSz",
	"5GurKGeTOXNkZ2SZEzkxMWW+JEtMOIZqDsnaQYNt5rsnrkkgXjM7hJC3BNYPrjakdk9tAqZDWEW+G+yN",
	"s9prruVmrOfmMVdBUJN4bYWfXwdVe5rhoRh7/ZUiWRE0KwlzspCAwipAfKh9qa34JzpolQuNuKJ5K4JQ",
	"U70r/qgeDE65EdzXluIHjRRjjLUTTteWE6soF/h+BG+MpSlZd8S11PYo7j1lLEf79e0ImLPckX8/gtJ7",
	"47I0tXh3XAhf1pPake38fsx1lV5y+qtESZ+Jl6nUhU4rFCrl6FC77s94gkqRHQf4sRJF6cfvBgNzf2xU",
	"MYLnkpUB6AXZ+jsRU4wnsqbDhEVVMJSBwjk6HF63pH48o5ZNuuGCYCLho31bcuxXYekOpWQfPl5CArP2",
	"LYIMZifB+uHooBGQwenx4PgUEjDoy2jhdNotDR8F+V0bXpBnfRBz4UGHiGijoS/zNuS6m9jo8E4Gg/9q",
	"M5Zx6Z42oUng58Hpw0sP3OHxxNZVhXbe1dAz9Fg4yG5gqVlFvtS5g9uwJu2vk71avPk8/GX4dl/9Q0OK",
	"8tjiPVeF7f7wRVRoebKe6AExws3qHq9BAB7ac6ldbOmjCPGxPdP5/Em90MNdabw0n67x3h8cTQI/PUXl",
	"tc7nu29Q0JBpy6KKDFkn5AOOXZ72J5u261mfa9jdlvdFLLti2Qvx+9SH2HUd1h7o2GFtPs03t6GRajsX",
	"F+drKyGDdHayugBDSJdhW8Lf9N2RpBn1F2z3tO9sSIC4P/JYXFhdmxZpK/bwft42/wYAAP//qGr/8zMP",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
