// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// Port defines model for Port.
type Port struct {
	Action   *string `json:"action,omitempty"`
	Port     *string `json:"port,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
}

// Rule defines model for Rule.
type Rule = string

// ChangePortResponseOK defines model for ChangePortResponseOK.
type ChangePortResponseOK struct {
	Data *string `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetPortsResponseOK defines model for GetPortsResponseOK.
type GetPortsResponseOK struct {
	Data *[]Port `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetRulesResponseOK defines model for GetRulesResponseOK.
type GetRulesResponseOK struct {
	Data *[]Rule `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetVersionResponseOK defines model for GetVersionResponseOK.
type GetVersionResponseOK struct {
	Data *string `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseServiceUnavailable defines model for ResponseServiceUnavailable.
type ResponseServiceUnavailable = BaseResponse

// OpenOrClosePortJSONRequestBody defines body for OpenOrClosePort for application/json ContentType.
type OpenOrClosePortJSONRequestBody = Port

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Rules
	// (GET /nftables)
	GetRules(ctx echo.Context) error
	// Open or Close a Port
	// (POST /nftables)
	OpenOrClosePort(ctx echo.Context) error
	// Get Version
	// (GET /nftables/version)
	GetVersion(ctx echo.Context) error
	// Get Opened Ports
	// (GET /port)
	GetOpenedPorts(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetRules converts echo context to params.
func (w *ServerInterfaceWrapper) GetRules(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetRules(ctx)
	return err
}

// OpenOrClosePort converts echo context to params.
func (w *ServerInterfaceWrapper) OpenOrClosePort(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.OpenOrClosePort(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// GetOpenedPorts converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenedPorts(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetOpenedPorts(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/nftables", wrapper.GetRules)
	router.POST(baseURL+"/nftables", wrapper.OpenOrClosePort)
	router.GET(baseURL+"/nftables/version", wrapper.GetVersion)
	router.GET(baseURL+"/port", wrapper.GetOpenedPorts)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RXUW/bNhD+K8RtDy2gWEKyAZ2APjQZVgQZ5iLptoc4MGjqLLGVSO5IOfEM/feBlGQ7",
	"tuvaWVO0T4ko+u77Pn68Oy1A6MpohcpZSBdAaI1WFsPDRcFVju80uetueXjl14VWDpXz/3JjSim4k1rF",
	"H6xWfs2KAise3pblcArp7QJ+JJxCCj/Eq3Rxu8/G59xinwCaaAGGtEFyskWRcReC4QOvTImQgq2FQGsh",
	"Ajc3YcGRVDk0zXJFTz6gcNDcRUDIs6Eq55A6qrHxmzK0gqTxqCGF4RU0EbxF55nab4GqdFiFhX2xPFpY",
	"MeZEfL5Tgn2Ur+sSvx/KHu1BlI859b+QrNTq27J4MvhlkHxZg/f5z3l2jf/UaN0BRJeIFlChtTz3uc95",
	"xvoQTfQ/xTiEwEbC/sc3SDMp8E/FZ1yWfNLifAqjLhJbD/VVmO1MvMwczPEoaLppnSWHxUbk7gUjdDUp",
	"zNhkzizSDIlZmSGTU+YKJGTSMq7mEK25DzaRbxuxiSAUoC1AXLQA1t2sDaptM0dgugirna+SnftIOy10",
	"+XivE+aQGxJBKBvpYsdWi6Im6eY3Xu4ev+8tY6c/YmAhvZgF8gwJIlC88iHe1K7QJP8N1lqB4EZe4bxV",
	"R6qp3j6VUZ0kZ8JI4WrC8IAjxRhj7QuraxLIKswkfz2CF4ZwimRPhC41nQRTYMoyTh9fjoBZEhbd6xEU",
	"zhmbxjHx+0EuXVFPaovUXYSB0FV8KfDvgpf4HkURlzrXccWligW3XNvuz3jClUIa+/BjJfPCjV8liXkY",
	"GJWP4KlgSx/oGdG6exlSjCdljfsByypnvPQQLrjlw5sW1NdH1KKJH7nAm0i64OsWHPtNEt7zsmRv3l1C",
	"BLO2TUEKs1Nvan+nuJGQwtkgGZxBBIa7Ilg4VlPnK0l4yNFt2/DF++Gvw5cQolAw8WUG6XIgCPd/bRA8",
	"TZJPteblvnjHNNFE8HNy9vmf7ino4ZbWVcVp3gJkPULHcwvpLfzRkmUVukJnFu5CYbGHsx4aVEO6KLUN",
	"s24gH3rNuc7mRw0Dnx/XQmk4Xtudk3gTwU/HqLvW+L/4wXgNmSYWVGScdUJ++oyaaGXTeOnto+3aDW9P",
	"Nez27Pcsll2h3C9I3w+PFMGLj1n4enmqEJufPs8iQ4uT9UD3aLHWmsPQ9bgp39752aodZmx4X1MJKcSz",
	"03jaVc0wfnUZNpX8Xd+flDjDvrR2Tb3DYZdAfIiHE8fzt6Rr00ba2LuXxl3zXwAAAP//dCWTp18PAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
