// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// Rule defines model for Rule.
type Rule = string

// GetRulesResponseOK defines model for GetRulesResponseOK.
type GetRulesResponseOK struct {
	Data *[]Rule `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ResponseServiceUnavailable defines model for ResponseServiceUnavailable.
type ResponseServiceUnavailable = BaseResponse

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Rules
	// (GET /nftables)
	GetRules(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetRules converts echo context to params.
func (w *ServerInterfaceWrapper) GetRules(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetRules(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/nftables", wrapper.GetRules)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xU32sbRxD+V5ZpHxI464RNoRzkIW1pMC5ViVP6YBkx2hvdbbK3u8zsyVbF/e9l986y",
	"LadqaGmepJ2Z++abX98etO+Cd+SiQLUHJgneCeXHO4rve0vyfjIurpJVexfJxfQXQ7BGYzTelR/Fu2QT",
	"3VKH2WvtYgPVzR6+ZdpABd+Uj8nKMU7KH1DoIQEMxR4C+0AczcihxpjBTKQuG05hJbYwFBB3gaACZMYd",
	"DI8Gv/5IOsJwWwAT1gtnd1BF7mlIQTWJZhNSNVDB4iohPTC7Jt4aTb873KKxuLb0Ba2ge+zCGNmRCDaJ",
	"w4SknkINxX9s25cU9NnEh8y5t89Aq+NRHGrYHyFPDsUUe3ZUq/VOCfGWWImpSZmNii0xKSMK3Q6Kx84A",
	"HDM/DEsiG9dAriQPttq/cBUgpHs2cXedqhh5otYksor+E+UxmMSxJayJoQCHXYJ428fWs/kzTwweVyaY",
	"K9qNSY3b+JfFLvv5/EIHo2PPlB+0dEopNTrE96xJdVQbfLOEV4FpQyxn2lvPZ7nXVKka+dPrJShhLRTf",
	"LKGNMUhVlox3s8bEtl/3Qjzt10z7rrzU9EeLlj6QbkvrG192aFypUdDL9LNao3PEqwS/cqZp4+r7+Tzc",
	"z4JrlvBvydoE9D+yjXcmp1itbU+nCZuuUWgThR9RcHE9kvr6jEY25bMtSEtkYl7qkZz62TDdobXq7W+X",
	"UMCWWMYd2p6nk/eBHAYDFVzM5rMLKCBgbPMKl24T04HmR0Px5Rq++rD4afEaMgrnJb6soTpIdj6rJ1J+",
	"Pp//nXge4srP6P1QwHfzi3/+9IRO5ivtuw55NxJUDwwjNgLVDfw6Fqs6iq2vBW6Hp5edpfD5Td/cJsUb",
	"JUayv2cLFZTb83IzNT2L4pThuHm/+LszS1t6mMykCRMPORBJEPdnEZt37PswIh3FnizjdvgrAAD//64y",
	"TDNgBwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
