root = "."
tmp_dir = ".air"

[build]
bin = "./dist/casaos-firewall-amd64_linux_amd64_v1/build/sysroot/usr/bin/casaos-firewall -c /etc/casaos/local-storage.conf"
cmd = "goreleaser build --rm-dist --snapshot -f .goreleaser.debug.yaml --id casaos-firewall-amd64"
delay = 1000
exclude_dir = [".air", "codegen", "frontend","build","dist"]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
full_bin = ""
send_interrupt = true
kill_delay = 2000