name: Release Raw Module

on:
    push:
        tags:
            - 'v*'
jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 16.x ]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            -   name: Install pnpm
                uses: pnpm/action-setup@v2
                with:
                    version: 8
  
            -   name: Get version
                id: get_version
                run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
           
            -   name: '输出 echo artifact'
                run: |
                    echo ${{ steps.version.outputs.value }}
                    echo github ${{ github }}
                    echo github.sha ${{ github.sha }}
                    echo env.VERSION ${{ steps.get_version.outputs.VERSION }}

            # setup node
            - name: Setup Node.js LTS
              uses: actions/setup-node@v4
              with:
                cache-dependency-path: frontend/pnpm-lock.yaml
                node-version: lts/hydrogen
                cache: 'pnpm'

            # install dependencies
            - name: Install dependencies
              working-directory: ./frontend
              run: |
                pnpm install

            - name: Build app
              working-directory: ./frontend
              run: pnpm build 

            -   run: |
                    mksquashfs raw/ zimaos_firewall.raw
            -   name: '更新 Update release'
                uses: zhanghengxin/git-release-private@ice
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    allow_override: true
                    gzip: false
                    prerelease: true
                    tag: ${{ steps.get_version.outputs.VERSION }}
                    files: ./zimaos_firewall.raw

            -   name: '更新 Update release'
                uses: zhanghengxin/git-release-private@ice
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    allow_override: true
                    gzip: false
                    prerelease: true
                    tag: ${{ steps.get_version.outputs.VERSION }}
                    files: ./zimaos_firewall.raw
      